
package restaurante.Vistas;

import javax.swing.JOptionPane;
import restaurante.AccesoDatos.MesaData;


public class FormularioMesa extends javax.swing.JInternalFrame {
    
    private MesaData md;
    

  
    public FormularioMesa() {
        initComponents();
        
        md=new MesaData();
        
        desactivarCampos();
        jbGuardarMesa.setEnabled(false);
        jbBorrarMesa.setEnabled(false);
        jbModificarMesa.setEnabled(false);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNroMesa = new javax.swing.JTextField();
        jbBuscarMesa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrbActivaMesa = new javax.swing.JRadioButton();
        jbNuevaMesa = new javax.swing.JButton();
        jbBorrarMesa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbModificarMesa = new javax.swing.JButton();
        jtDescripMesa = new javax.swing.JTextField();
        jbGuardarMesa = new javax.swing.JButton();

        jLabel1.setText("Formulario Mesa");

        jLabel2.setText("Numero de Mesa:");

        jbBuscarMesa.setText("Buscar");

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Estado:");

        jrbActivaMesa.setText("Activa");

        jbNuevaMesa.setText("Nueva");

        jbBorrarMesa.setText("Borrar");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jbModificarMesa.setText("Modificar");

        jbGuardarMesa.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbNuevaMesa)
                                .addGap(18, 18, 18)
                                .addComponent(jbGuardarMesa)
                                .addGap(18, 18, 18)
                                .addComponent(jbModificarMesa)
                                .addGap(18, 18, 18)
                                .addComponent(jbBorrarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtDescripMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtNroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbBuscarMesa))
                                    .addComponent(jrbActivaMesa))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtNroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarMesa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDescripMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrbActivaMesa))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevaMesa)
                    .addComponent(jbBorrarMesa)
                    .addComponent(jButton4)
                    .addComponent(jbModificarMesa)
                    .addComponent(jbGuardarMesa))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int eleccion = JOptionPane.showConfirmDialog(this, "Realmente desea salir?", "Confirmacion", JOptionPane.YES_NO_OPTION);
            if (eleccion== JOptionPane.YES_OPTION){
                dispose();
            }else if (eleccion== JOptionPane.NO_OPTION){
                JOptionPane.showConfirmDialog(null, "Desea seguir trabajando?", "Confirmacion", JOptionPane.CLOSED_OPTION);
            }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbBorrarMesa;
    private javax.swing.JButton jbBuscarMesa;
    private javax.swing.JButton jbGuardarMesa;
    private javax.swing.JButton jbModificarMesa;
    private javax.swing.JButton jbNuevaMesa;
    private javax.swing.JRadioButton jrbActivaMesa;
    private javax.swing.JTextField jtDescripMesa;
    private javax.swing.JTextField jtNroMesa;
    // End of variables declaration//GEN-END:variables


    private void desactivarCampos(){
        jtDescripMesa.setEnabled(false);
        jrbActivaMesa.setEnabled(false);                    
    } 
    
    private void activarCampos(){
        jtNroMesa.setEnabled(true);
        jtDescripMesa.setEnabled(true);
        jrbActivaMesa.setEnabled(true);
    }
    
    private void limpiar(){
        jtNroMesa.setText("");
        jtDescripMesa.setText("");
        jrbActivaMesa.setSelected(false);
    }
    
}
