/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Munu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbListaProducto = new javax.swing.JButton();
        jbRegistroMesa = new javax.swing.JButton();
        jbRegistroProducto = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbComanda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jbListaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/menu-del-restaurante (1).png"))); // NOI18N
        jbListaProducto.setText("Lista de Productos");
        jbListaProducto.setContentAreaFilled(false);
        jbListaProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbListaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaProductoActionPerformed(evt);
            }
        });

        jbRegistroMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mesa.png"))); // NOI18N
        jbRegistroMesa.setText("Mesa");
        jbRegistroMesa.setContentAreaFilled(false);
        jbRegistroMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistroMesaActionPerformed(evt);
            }
        });

        jbRegistroProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bienes.png"))); // NOI18N
        jbRegistroProducto.setText("Producto");
        jbRegistroProducto.setContentAreaFilled(false);
        jbRegistroProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistroProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Georgia", 2, 20)); // NOI18N
        jLabel4.setText("ADMINISTRACION");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/klipartz.com (1).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 20)); // NOI18N
        jLabel5.setText("PEDIDOS");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lista.png"))); // NOI18N
        jButton1.setText("Registro");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lista-de-la-compra.png"))); // NOI18N
        jbComanda.setText("Comanda");
        jbComanda.setContentAreaFilled(false);
        jbComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbRegistroMesa)
                                    .addComponent(jButton1))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbComanda)
                                            .addComponent(jbRegistroProducto)))))
                            .addComponent(jbListaProducto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbComanda))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegistroMesa)
                    .addComponent(jbRegistroProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jbListaProducto)
                .addContainerGap(272, Short.MAX_VALUE))
            .addComponent(escritorio)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbListaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaProductoActionPerformed
        // TODO add your handling code here:

        escritorio.removeAll();
        escritorio.repaint();
        ListaDeProductos lisP =new ListaDeProductos();
        lisP.setVisible(true);
        escritorio.add(lisP);
        escritorio.moveToFront(lisP);
        
    }//GEN-LAST:event_jbListaProductoActionPerformed

    private void jbRegistroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistroMesaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMesa mesa=new FormularioMesa();
        mesa.setVisible(true);
        escritorio.add(mesa);
        escritorio.moveToFront(mesa);
    }//GEN-LAST:event_jbRegistroMesaActionPerformed

    private void jbRegistroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistroProductoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioProducto producto=new FormularioProducto();
        producto.setVisible(true);
        escritorio.add(producto);
        escritorio.moveToFront(producto);
    }//GEN-LAST:event_jbRegistroProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioIngreso ingresar=new FormularioIngreso();
        ingresar.setVisible(true);
        escritorio.add(ingresar);
        escritorio.moveToFront(ingresar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComandaActionPerformed
        // TODO add your handling code here:

        escritorio.removeAll();
        escritorio.repaint();
        FormularioComanda ingresar = new FormularioComanda();
        ingresar.setVisible(true);
        escritorio.add(ingresar);
        escritorio.moveToFront(ingresar);
    }//GEN-LAST:event_jbComandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbComanda;
    private javax.swing.JButton jbListaProducto;
    private javax.swing.JButton jbRegistroMesa;
    private javax.swing.JButton jbRegistroProducto;
    // End of variables declaration//GEN-END:variables
}
